# yarn berry の設定ファイル
# cf. https://yarnpkg.com/configuration/manifest

# yarn 本体を Git にコミットして使う
yarnPath: .yarn/releases/yarn-3.3.0.cjs

# パッケージのインストール方法を pnp ではなく node_modules にする
nodeLinker: node-modules
